using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;
using AutoMapper;
using Microsoft.Extensions.Logging;
using NiveshX.Core.DTOs.Country;
using NiveshX.Core.Exceptions;
using NiveshX.Core.Interfaces;
using NiveshX.Core.Interfaces.Services;
using NiveshX.Core.Models;

namespace NiveshX.Infrastructure.Services
{
    public class CountryService : BaseService, ICountryService
    {
        public CountryService(
            IUnitOfWork unitOfWork,
            ILogger<CountryService> logger,
            IUserContext userContext,
            IMapper mapper)
            : base(unitOfWork, logger, userContext, mapper)
        { }

        public async Task<IEnumerable<CountryResponse>> GetAllAsync(CancellationToken cancellationToken = default)
        {
            try
            {
                Logger.LogInformation("Fetching all countries");
                var countries = await UnitOfWork.Countries.GetAllAsync(cancellationToken);
                return Mapper.Map<IEnumerable<CountryResponse>>(countries);
            }
            catch (Exception ex)
            {
                Logger.LogError(ex, "Error occurred while fetching countries");
                throw;
            }
        }

        public async Task<CountryResponse?> GetByIdAsync(Guid id, CancellationToken cancellationToken = default)
        {
            try
            {
                Logger.LogInformation("Fetching country with ID: {CountryId}", id);
                var country = await UnitOfWork.Countries.GetByIdAsync(id, cancellationToken);
                return country == null ? null : Mapper.Map<CountryResponse>(country);
            }
            catch (Exception ex)
            {
                Logger.LogError(ex, "Error occurred while fetching country with ID: {CountryId}", id);
                throw;
            }
        }

        public async Task<CountryResponse> CreateAsync(CreateCountryRequest request, CancellationToken cancellationToken = default)
        {
            try
            {
                Logger.LogInformation("Creating new country: {Code}", request.Code);

                var exists = await UnitOfWork.Countries.ExistsAsync(request.Code, request.Name, cancellationToken);
                if (exists)
                    throw new DuplicateEntityException("A country with the same code or name already exists.");

                var country = Mapper.Map<Country>(request);

                // Audit helper from BaseService sets CreatedOn/CreatedBy/IsActive/IsDeleted
                SetCreatedAudit(country);

                // Id should be generated by entity default or EF; remove manual Guid.NewGuid() to avoid duplication
                await UnitOfWork.Countries.AddAsync(country, cancellationToken);
                await UnitOfWork.SaveChangesAsync(cancellationToken);

                Logger.LogInformation("Country created successfully: {CountryId}", country.Id);
                return Mapper.Map<CountryResponse>(country);
            }
            catch (Exception ex)
            {
                Logger.LogError(ex, "Error occurred while creating country: {Code}", request.Code);
                throw;
            }
        }

        public async Task<CountryResponse?> UpdateAsync(Guid id, UpdateCountryRequest request, CancellationToken cancellationToken = default)
        {
            try
            {
                Logger.LogInformation("Updating country with ID: {CountryId}", id);
                var country = await UnitOfWork.Countries.GetByIdAsync(id, cancellationToken);
                if (country == null)
                {
                    throw new NotFoundException($"Country not found for update: {id}.");
                }

                var duplicate = await UnitOfWork.Countries.ExistsAsync(request.Code, request.Name, excludeId: id, cancellationToken);
                if (duplicate)
                    throw new DuplicateEntityException("A country with the same code or name already exists.");

                // Map incoming request onto existing entity
                Mapper.Map(request, country);

                // Set modified audit using BaseService helper
                SetModifiedAudit(country);

                await UnitOfWork.Countries.UpdateAsync(country, cancellationToken);
                await UnitOfWork.SaveChangesAsync(cancellationToken);

                Logger.LogInformation("Country updated successfully: {CountryId}", id);
                return Mapper.Map<CountryResponse>(country);
            }
            catch (Exception ex)
            {
                Logger.LogError(ex, "Error occurred while updating country with ID: {CountryId}", id);
                throw;
            }
        }

        public async Task<bool> DeleteAsync(Guid id, CancellationToken cancellationToken = default)
        {
            try
            {
                Logger.LogInformation("Attempting to delete country with ID: {CountryId}", id);

                // Prefer service-driven soft-delete to ensure audit fields are populated
                var country = await UnitOfWork.Countries.GetByIdAsync(id, cancellationToken) ?? throw new NotFoundException($"Country not found for deletion: {id}.");

                // mark soft-deleted and set audit info
                country.IsDeleted = true;
                SetModifiedAudit(country);

                await UnitOfWork.Countries.UpdateAsync(country, cancellationToken);
                await UnitOfWork.SaveChangesAsync(cancellationToken);

                Logger.LogInformation("Country deleted successfully: {CountryId}", id);
                return true;
            }
            catch (Exception ex)
            {
                Logger.LogError(ex, "Error occurred while deleting country with ID: {CountryId}", id);
                throw;
            }
        }
    }
}
